### ISSUE TITLE
Table Conversion

### ISSUE THREAD

**Issue by chrisgriffith** [chrisgriffith/glasstone-dolan#1]
A breakdown of the number of tables per chapter. 
- [ ] Chapter 3: 3 tables
- [ ] Chapter 4: 1 tables
- [ ] Chapter 5: 7 tables
- [ ] Chapter 6: 3 tables
- [ ] Chapter 7: 6 tables
- [ ] Chapter 8: 4 tables
- [ ] Chapter 9: 7 tables
- [ ] Chapter 10: 5 tables
- [ ] Chapter 11: 4 tables
- [ ] Chapter 12: 12 tables

**Comment by meyerweb** [comment]
I think this might be clear now?
