### ISSUE TITLE
Centering Equations

### ISSUE THREAD

**Issue by chrisgriffith** [chrisgriffith/glasstone-dolan#30]
Some equations are not centering. Here are the ones not centering (OSX 11.6.5, Chrome 99.0.4844)
3.55.1
3.56.1
3.56.2
3.61.1
3.61.2
3.62.1
3.65.1
3.65.2
3.65.3
3.65.4
7.73.1
7.74.1
7.77.1
7.79.1
7.82.1
7.83.1
7.94.1
7.95.1
7.96.1
7.96.2
7.96.3
7.96.4
10.123.1
10.124.1
10.127.1
10.130.1
10.130.2
10.133.1
10.133.2
10.134.1
10.138.1
10.139.1
10.140.1
10.142.1
10.145.1
10.146.1
10.147.1
10.148.1
10.149.1
10.150.1
10.150.2
10.154.1
10.156.1
10.157.1
10.163.1

**Comment by meyerweb** [comment]
I believe this can be closed thanks to PR #34.

**Comment by meyerweb** [comment]
This should be closed, but I don’t have the option to close it, only to comment.

**Comment by chrisgriffith** [comment]
Done
